services:
  til-finals:
    image: asia-southeast1-docker.pkg.dev/til-ai-2026/repo-til-26-pandamonium/pandamonium-server:finals
  til-ae:
    image: pandamonium-ae:finals
  til-asr:
    image: asia-southeast1-docker.pkg.dev/til-ai-2026/repo-til-26-pandamonium/pandamonium-asr:v32
  til-cv:
    image: asia-southeast1-docker.pkg.dev/til-ai-2026/repo-til-26-pandamonium/pandamonium-cv:v54
  til-nlp:
    image: asia-southeast1-docker.pkg.dev/til-ai-2026/repo-til-26-pandamonium/pandamonium-nlp:v58
  til-noise:
    image: asia-southeast1-docker.pkg.dev/til-ai-2026/repo-til-26-pandamonium/pandamonium-noise:v20